# -*- coding: utf-8 -*-
"""LVADSUSR123_FA_LAB3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xoz5WPhRyfHzBW0toaagJRMWHn1Crwin
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/content/sample_data/seeds.csv')

print(data.describe())
print()

missing_values = data.isnull().sum()
print("Missing values per column:\n", missing_values)
print()

data.fillna(data.mean(), inplace=True)

sns.heatmap(data.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()
print()

sns.boxplot(data=data)
plt.title("Boxplot of Variables")
plt.xticks(rotation=45)
plt.show()
print()

for col in data.select_dtypes(include=[np.number]).columns:
    ninety_fifth_percentile = data[col].quantile(0.95)
    data[col] = np.where(data[col] > ninety_fifth_percentile, ninety_fifth_percentile, data[col])

sns.boxplot(data=data)
plt.title("Boxplot of Variables after Handling Outliers")
plt.xticks(rotation=45)
plt.show()
print()

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

sse = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(scaled_data)
    sse.append(kmeans.inertia_)

plt.plot(range(1, 11), sse, marker='o', linestyle='--')
plt.title('Elbow plot')
plt.xlabel('Number of Clusters')
plt.ylabel('Sum of squared error (SSE)')
plt.xticks(range(1, 11))
plt.grid(True)
plt.show()
print()

kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(scaled_data)
data['cluster'] = kmeans.labels_

plt.scatter(data['Length of kernel'], data['Width of kernel'], c=data['cluster'], cmap='viridis')
plt.xlabel('Length of kernel')
plt.ylabel('Width of kernel')
plt.title('Clusters of Seed Data')
plt.show()
print()

cluster_summary = data.groupby('cluster').mean()
print(cluster_summary)
print()