# -*- coding: utf-8 -*-
"""LVADSUSR123_FA_LAB2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nLvYWEU56fDg8kMPZ_SiJh5G7vBcGoo7
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

data = pd.read_csv('/content/sample_data/auto-mpg.csv')

print(data.describe())
print()

plt.figure(figsize=(10, 8))
sns.heatmap(data.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()
print()

print("Missing values per column:\n", data.isnull().sum())
data.fillna(data.mean(), inplace=True)

plt.figure(figsize=(12, 6))
sns.boxplot(data=data)
plt.title("Boxplot of Variables")
plt.xticks(rotation=45)
plt.show()
print()

for col in data.select_dtypes(include=[np.number]).columns:
    ninety_fifth_percentile = data[col].quantile(0.95)
    data[col] = np.where(data[col] > ninety_fifth_percentile, ninety_fifth_percentile, data[col])

plt.figure(figsize=(12, 6))
sns.boxplot(data=data)
plt.title("Boxplot of Variables after Handling Outliers")
plt.xticks(rotation=45)
plt.show()

data = data.replace('?', np.nan)
data = data.dropna()

X = data.drop('mpg', axis=1)
y = data['mpg']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train_encoded = pd.get_dummies(X_train)
X_test_encoded = pd.get_dummies(X_test)

X_train_encoded, X_test_encoded = X_train_encoded.align(X_test_encoded, join='outer', axis=1, fill_value=0)

model = LinearRegression()
model.fit(X_train_encoded, y_train)

y_pred = model.predict(X_test_encoded)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

rmse = mean_squared_error(y_test, y_pred, squared=False)

print("Mean Squared Error:", mse)
print()
print("R-squared:", r2)
print()
print("Root Mean Squared Error (RMSE):", rmse)
print()